version: '3.8'

services:
  db:
    image: postgres:16
    container_name: coffee-machine-db
    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local